const data = {
    products: [
        {
            _id: '1',
            name: 'L 42 Sunglasses',
            category: 'Accessory',
            image: '/images/sunglasses.jpg',
            price: 120,
            brand: 'L 42',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'L 42 Sunglasses',
            category: 'Accessory',
            image: '/images/sunglasses.jpg',
            price: 5,
            brand: 'L 42',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'L 42 Sunglasses',
            category: 'Accessory',
            image: '/images/sunglasses.jpg',
            price: 160,
            brand: 'L 42',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'L 42 Sunglasses',
            category: 'Accessory',
            image: '/images/sunglasses.jpg',
            price: 120,
            brand: 'L 42',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'L 42 Sunglasses',
            category: 'Accessory',
            image: '/images/sunglasses.jpg',
            price: 20,
            brand: 'L 42',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'L 42 Sunglasses',
            category: 'Accessory',
            image: '/images/sunglasses.jpg',
            price: 220,
            brand: 'L 42',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};

export default data;